# Created by: Matt Haught <matt@haught.org>
# $FreeBSD$

PORTNAME=	resolve-hostname
PORTVERSION=	0.0.4
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	With caching, selector for IPv4/IPv6, and many other features

LICENSE=	BSD2CLAUSE RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
