# $FreeBSD$

PORTNAME=	fluent-plugin-string-scrub
PORTVERSION=	0.1.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Fluent plugin for string scrub.

RUN_DEPENDS=	\
	rubygem-fluentd>0:${PORTSDIR}/sysutils/rubygem-fluentd

USE_RUBY=	yes
USES=           gem

.include <bsd.port.mk>
