# Created by: Matt Haught <matt@haught.org>
# $FreeBSD$

PORTNAME=	proxifier
PORTVERSION=	1.0.3
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Proxifier adds support for HTTP or SOCKS proxies and lets you \
		force TCPSocket to use proxies.

LICENSE=	BSD2CLAUSE RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
